export { default as Home } from "./Home"
export { default as Contact } from "./Contact"
export { default as New } from "./New"
export { default as Shop } from "./Shop"
export { default as Productdetail } from "./Productdetail"
export { default as Watersports } from "./WaterSports"
export { default as Camping } from "./Camping"
export { default as Hiking } from "./Hiking"